version: '2'

services:
  python:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'docker.io/bitnami/python:3.6-prod-debian-10'
    ports:
      - 8000:8000
    volumes:
      - .:/app
